version: "3.4"

services:
  demo-django-frontend:
    build: .
    image: codescope/demo-django:$COMMIT
    command: ["scope-run", "gunicorn", "demo.wsgi", "-b", "0.0.0.0:8000"]
    environment:
      - CI
      - SCOPE_APIKEY
      - SCOPE_API_ENDPOINT
      - SCOPE_SERVICE=frontend
      - REDIS_HOST=redis
    links:
      - redis

  demo-django-worker:
    build: .
    image: codescope/demo-django:$COMMIT
    command: ["scope-run", "celery", "-A", "demo", "worker", "-P", "solo", "-l", "debug"]
    environment:
      - CI
      - SCOPE_APIKEY
      - SCOPE_API_ENDPOINT
      - SCOPE_SERVICE=worker
      - REDIS_HOST=redis
    links:
      - redis

  redis:
    image: redis

  tests-worker:
    build: .
    image: codescope/demo-django:$COMMIT
    command: ["scope-run", "./manage.py", "test", "-p", "tests_worker.py"]
    environment:
      - CI
      - SCOPE_APIKEY
      - SCOPE_API_ENDPOINT
      - SCOPE_SERVICE=worker
      - REDIS_HOST=redis
      - JENKINS_URL
      - BUILD_ID
      - BUILD_NUMBER
      - BUILD_URL
    links:
      - redis
    depends_on:
      - demo-django-worker

  tests-frontend:
    build: .
    image: codescope/demo-django:$COMMIT
    command: ["scope-run", "./manage.py", "test", "-p", "tests_frontend.py"]
    environment:
      - CI
      - SCOPE_APIKEY
      - SCOPE_API_ENDPOINT
      - SCOPE_SERVICE=frontend
      - FRONTEND_HOST=demo-django-frontend
      - REDIS_HOST=redis
      - JENKINS_URL
      - BUILD_ID
      - BUILD_NUMBER
      - BUILD_URL
    links:
      - demo-django-frontend
      - demo-django-worker
